jake-codes-at-5-am/npoi

main/HSSF/UserModel/HSSFCell.cs, main/SS/UserModel/Cell.cs, ooxml/XSSF/Streaming/SXSSFCell.cs, ooxml/XSSF/UserModel/XSSFCell.cs, ooxml/XSSF/UserModel/XSSFSheet.cs, testcases/ooxml/POIFS/Crypt/TestSecureTempZip.cs, testcases/ooxml/POIFS/Crypt/TestSignatureInfo.cs
=> Upstream sync

OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotCacheDefinition.cs, OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotCacheRecords.cs, OpenXmlFormats/Spreadsheet/PivotTable/CT_PivotTableDefinition.cs, OpenXmlFormats/Spreadsheet/Sheet.cs, OpenXmlFormats/Spreadsheet/Workbook/CT_Workbook.cs, openxml4Net/Util/XmlHelper.cs, testcases/main/NPOI.TestCases.csproj, testcases/ooxml/NPOI.OOXML.TestCases.csproj, testcases/openxml4net/NPOI.OOXML4Net.Testcases.csproj
Fix pivot table serialization issues
=> Iron-37 fix

main/SS/UserModel/Charts/BarChartData.cs, main/SS/UserModel/Charts/BarChartSeries.cs, ooxml/XSSF/UserModel/Charts/XSSFBarChartData.cs
We've changed places for categories and values for this type of chart, this reverts that change and returns to original form.
=> Revert bar chart changes

main/SS/Formula/OperationEvaluationContext.cs, main/SS/Formula/WorkbookEvaluator.cs, main/SS/UserModel/DateUtil.cs
=> Upstream pull 20220630

ooxml/Iron/Util/XSSFCellUtil.cs
Thus it wsn't updating. This fixes the issue.
=> ShrinkToFit property got left out of the booleanValues list

main/HSSF/UserModel/HSSFSheet.cs, main/SS/UserModel/Sheet.cs, main/SS/Util/SheetUtil.cs, ooxml/XSSF/Streaming/SXSSFSheet.cs, ooxml/XSSF/UserModel/XSSFSheet.cs, testcases/main/HSSF/UserModel/TestHSSFSheet.cs, testcases/main/SS/Util/TestSheetUtil.cs, testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
Implementation for AutoSizeRow method, that works similarly to AutoSizeColumn, but adjusts the height of a specified row.
Complete with tests.
=> Iron-41 auto row height

ooxml/Iron/Util/XSSFCellUtil.cs
XSSFCellUtil keeps ducking up, this fixes FillPattern comparison bug and cleans-up the code of the class a little bit.
=> Fix duplicate styles on style change

OpenXmlFormats/NPOI.OpenXmlFormats.Multitarget.csproj, main/NPOI.Multitarget.csproj, ooxml/NPOI.OOXML.Multitarget.csproj, openxml4Net/NPOI.OpenXml4Net.Multitarget.csproj, solution/NPOI.Multitarget.sln
=> Prepare for release

OpenXmlFormats/Spreadsheet/Sheet/CT_Col.cs, OpenXmlFormats/Spreadsheet/Sheet/CT_Cols.cs, OpenXmlFormats/Spreadsheet/Sheet/CT_Comment.cs, OpenXmlFormats/Vml/Main.cs, main/HSSF/UserModel/HSSFSheet.cs, main/SS/Formula/FormulaShifter.cs, main/SS/UserModel/Helpers/RowShifter.cs, main/SS/UserModel/Sheet.cs, main/SS/Util/CellUtil.cs, main/SS/Util/SheetUtil.cs, ooxml/XSSF/Streaming/SXSSFSheet.cs, ooxml/XSSF/UserModel/Helpers/ColumnHelper.cs, ooxml/XSSF/UserModel/Helpers/XSSFRowColShifter.cs, ooxml/XSSF/UserModel/XSSFCell.cs, ooxml/XSSF/UserModel/XSSFRow.cs, ooxml/XSSF/UserModel/XSSFSheet.cs, testcases/main/HSSF/UserModel/TestHSSFSheet.cs, testcases/ooxml/XSSF/UserModel/TestXSSFSheet.cs
Lots of changes here, some bug fixes, but generally just readability changes
=> Refactoring and clean up

main/SS/UserModel/Chart.cs, ooxml/XSSF/UserModel/XSSFChart.cs
To be able to controll appearance of the chart title
=> Upstream-feature: Add IChart.SetTitleOverlay(bool) method.

ooxml/XSSF/UserModel/XSSFSheet.cs, testcases/main/HSSF/Extractor/TestOldExcelExtractor.cs, testcases/main/SS/Formula/Atp/TestNetworkdaysFunction.cs, testcases/main/SS/Formula/Functions/TestBesselJ.cs, testcases/main/SS/Formula/Functions/TestComplex.cs, testcases/main/SS/Formula/Functions/TestDec2Bin.cs, testcases/main/SS/Formula/Functions/TestDec2Hex.cs, testcases/main/SS/Formula/Functions/TestDelta.cs, testcases/main/SS/Formula/Functions/TestDollarDe.cs, testcases/main/SS/Formula/Functions/TestDollarFr.cs, testcases/main/SS/Formula/Functions/TestFixed.cs, testcases/main/SS/Formula/Functions/TestNormDist.cs, testcases/main/SS/Formula/Functions/TestNormInv.cs, testcases/main/SS/Formula/Functions/TestNormSDist.cs, testcases/main/SS/Formula/Functions/TestNormSInv.cs, testcases/main/SS/Formula/Functions/TestNumberValue.cs, testcases/main/SS/Formula/Functions/TestNumericFunction.cs, testcases/main/SS/Formula/Functions/TestQuotient.cs, testcases/main/SS/Formula/Functions/TestStandardize.cs, testcases/main/SS/Formula/Functions/TestTDist.cs, testcases/main/SS/Formula/Functions/TestText.cs, testcases/main/SS/UserModel/TestFractionFormat.cs, testcases/main/Util/TestStringUtil.cs, testcases/ooxml/XSSF/Streaming/SheetDataWriterTests.cs, testcases/ooxml/XSSF/UserModel/TestXSSFTextRun.cs, testcases/ooxml/XSSF/UserModel/TestXSSFWorkbook.cs
Fix XSSFSheet.RemoveOverwrittenColumns
it was unnecessarily creating all columns, not just the ones that need clearing
=> Xssfcolumn

ooxml/XSSF/UserModel/XSSFSheet.cs, testcases/main/SS/Formula/Functions/TestNormSInv.cs
It was moving cells to the columns that were then also shifted, shifting these cells extra times
=> Fix bug with column shifting

.github/workflows/npoi-testing.yml, testcases/main/NPOI.TestCases.Multitarget.csproj, testcases/ooxml/NPOI.OOXML.TestCases.Multitarget.csproj, testcases/openxml4net/NPOI.OOXML4Net.TestCases.Multitarget.csproj
Use net481 and net6.0 target frameworks for tests
=> Simplify project

OpenXmlFormats/Spreadsheet/Sheet.cs, main/HSSF/Record/Aggregates/DataValidityTable.cs, main/HSSF/Record/DVRecord.cs, main/HSSF/UserModel/HSSFSheet.cs, main/SS/UserModel/Sheet.cs, ooxml/XSSF/Streaming/SXSSFSheet.cs, ooxml/XSSF/UserModel/XSSFSheet.cs, testcases/main/HSSF/UserModel/TestDataValidation.cs, testcases/ooxml/XSSF/UserModel/TestXSSFDataValidation.cs
The method removes data validation from the sheet.
=> Add ISheet.RemoveValidationData method

main/NPOI.Multitarget.csproj
=> update irondrawing to 2024.5.1

main/NPOI.Multitarget.csproj
Update IronSoftware.System.Drawing to 2024.6.1
=> NPOI.Multitarget.csproj: Update drawing to 2024.6.1

main/NPOI.Multitarget.csproj
update iron drawing to 2024.7.2
=> for Release 2024.7

main/NPOI.Multitarget.csproj
=> for Release 2024.9

main/NPOI.Multitarget.csproj
- Update IronSoftware.System.Drawing to v2024.9.15
=> Prepare for December release

OpenXmlFormats/NPOI.OpenXmlFormats.Core.csproj, OpenXmlFormats/NPOI.OpenXmlFormats.Multitarget.csproj, main/NPOI.Core.csproj, main/NPOI.Multitarget.csproj, ooxml/NPOI.OOXML.Core.csproj, ooxml/NPOI.OOXML.Multitarget.csproj, openxml4Net/NPOI.OpenXml4Net.Core.csproj, openxml4Net/NPOI.OpenXml4Net.Multitarget.csproj
Multitarget solution builds as expected
=> Updated Nuget packages mimicing NPOI

main/HSSF/Model/RecordOrderer.cs, main/NPOI.Multitarget.csproj, ooxml/XSSF/UserModel/XSSFTableStyle.cs
Aggregated changes for XL-183 and XL-154
=> Npoi aggregated changes

ooxml/NPOI.OOXML.Multitarget.csproj
Update System.Security.Cryptography.Pkcs to v 6.0.5 to fix vulnerable.
=> Fix: Update System.Security.Cryptography.Pkcs to v6.0.5

main/NPOI.Multitarget.csproj
- Update drawing version to 2025.1.6
=> For January 2025 Release

main/NPOI.Multitarget.csproj
Update IronSoftware.System.Drawing v2025.3.6
=> Prepare to release 2025.4
